# check if tests succeed
sudo: required
language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - docker build -t testdocker .
  - docker network create -d bridge mongodb-net
  - docker run -d --net=mongodb-net --name=mongodb mongo:3.4

install:
  - pip install travis-sphinx
  - pip install sphinx_rtd_theme
  - pip install ghp_import
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py install"

script:
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py test"
  - travis-sphinx build

after_success:
  - travis-sphinx deploy