# check if tests succeed
sudo: required
language: python

services:
  - docker

before_install:
  - docker build -t testdocker .
  - docker run testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py test"

#install: "python setup.py install"
#script: "python setup.py test"