# check if tests succeed
sudo: required
language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - $(printenv | grep -E '^TRAVIS_' | sed 's/TRAVIS_/-e /g') > .env
  - docker build -t testdocker .
  - docker network create -d bridge mongodb-net
  - docker run -d --net=mongodb-net --name=mongodb mongo:3.4

install:
  #- pip install travis-sphinx
  # - pip install sphinx_rtd_theme
  #- pip install ghp_import
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3 setup.py install"

script:
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3 setup.py test"
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3 setup.py install; make html"

after_success:
  - docker run --env-file .env --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3 setup.py install; make deploy"