# check if tests succeed
sudo: required
language: python

services:
  - docker

before_install:
  - docker build -t testdocker .
  - docker run -itd --name=mongodb mongo:3.4 /bin/bash

install:
  - docker run -itd --link mongodb testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py install"

script:
  - docker run -itd --link mongodb testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py test"