# check if tests succeed
sudo: required
language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - printenv | grep -E '^TRAVIS_' > .env
  - docker build -t testdocker .
  - docker network create -d bridge mongodb-net
  - docker run -d --net=mongodb-net --name=mongodb mongo:3.4

install:
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py install"

script:
  - docker run --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py test"

after_success:
  - docker run --env-file .env --net=mongodb-net testdocker /bin/sh -c "cd /root/vcsshark; make deploy > /dev/null"
  - SRD=`docker ps -alq` && docker cp $SRD:/root/vcsshark/plugin_packaging/vcsSHARK_plugin.tar .

deploy:
  provider: releases
  api_key: ${TRAVIS_GH_TOKEN}
  file: "vcsSHARK_plugin.tar"
  skip_cleanup: true
  on:
    repo: smartshark/vcsSHARK
    tags: true