# check if tests succeed
sudo: required
language: python
python:
  - "3.6"

services:
  - mongodb

before_install:
  - printenv | grep -E '^TRAVIS_' > .env
  # Create libgit2 library in separate folder, otherwise it overwrites our makefile
  - mkdir libgit2
  - cd libgit2
  - wget https://github.com/libgit2/libgit2/archive/v0.26.2.tar.gz
  - tar xzf v0.26.2.tar.gz
  - cmake libgit2-0.26.2/
  - make
  - sudo make install
  - cd ..
  # --- libit2 install finished ---
  - sudo apt-get install -y build-essential wget git
  - sudo apt-get install -y python3-pip python3-cffi
  - pip install -U pip setuptools
  - pip install Sphinx
  - pip install sphinx_rtd_theme
  - pip install ghp_import

install:
  - python setup.py install
  - sudo ldconfig

script:
  - python setup.py test
  - make html

after_success:
  - cd plugin_packaging && ./build_plugin.sh && cd ..

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file: "plugin_packaging/vcsSHARK_plugin.tar"
    skip_cleanup: true
    on:
      repo: smartshark/vcsSHARK
      tags: true
  - provider: pages
    github-token: $(GH_TOKEN}
    local-dir: $TRAVIS_BUILD_DIR/docs/build
    skip_cleanup: true
    on:
      branch: master