# check if tests succeed
sudo: required
language: python

services:
  - docker

before_install:
  - docker build -t testdocker .
  - docker network create -d bridge mongodb-net
  - docker run -d --net=mongodb-net --name=mongodb mongo:3.4

install:
  - docker run --net=mongodb-net --name client testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py install"

script:
  - docker run --net=mongodb-net --name client testdocker /bin/sh -c "cd /root/vcsshark; python3.5 setup.py test"